name: init vue-electron-app
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps: 
      - name: get repository code
        uses: actions/checkout@v3
      - name: install dependecies
        # run: npm install  
        run: npm ci
      - name: test application
        run: npm --version  


