name: build & deploy

on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: get repository code
        uses: actions/checkout@v3
      
      - name: install dependecies
        run: npm install

      # - name: install vue/cli
      #   npm install -g @vue/cli

      - name: build application
        run: npm run build
        # run: npm electron build

      - name: upload artifact
        uses: actions/upload-artifact@v3 
        
        with:
          path: dist
          # path: dist_electron
          name: dist-files 

  deploy:
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - name: get build project
        uses: actions/download-artifact@v3 

        with: 
          name: dist-files  



