name: init vue-electron-app
on: push
jobs:
  init:
    runs-on: ubuntu-20.04
    steps: 
      - name: get repository code
        uses: actions/checkout@v3
      - name: install dependecies
        # run: npm ci
        run: npm install
      - name: test application
        run: npm --version
        

